default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: github_issues_explorer_development
  username: github_issues_explorer_local
  password: foobar123 

test:
  <<: *default
  database: github_issues_explorer_test
  username: github_issues_explorer_local
  password: foobar123 

production:
  <<: *default
  database: <%= ENV['GITHUB_ISSUES_EXPLORER_DB'] %>
  username: <%= ENV['GITHUB_ISSUES_EXPLORER_DB_USER'] %>
  password: <%= ENV['GITHUB_ISSUES_EXPLORER_DB_PASSWORD'] %>
